kyma-project/nats-manager

.gitignore, resources/nats/.helmignore, resources/nats/Chart.yaml, resources/nats/README.md, resources/nats/templates/_helpers.tpl, resources/nats/templates/accounts-secret.yaml, resources/nats/templates/configmap.yaml, resources/nats/templates/destination-rule.yaml, resources/nats/templates/service.yaml, resources/nats/templates/statefulset.yaml, resources/nats/values.yaml
- Copied local NATS helm charts from [kyma](https://github.com/kyma-project/kyma/tree/main/resources/eventing/charts/nats). (First commit)
- There are no major changes in upstream NATS helm chart. Only `PodDisruptionPolicy` is introduced. It will be discussed later whether we want to include `PodDisruptionPolicy`.
- Added `accounts-secret.yaml` for accounts.
Test: `helm install --namespace=kyma-system eventing .` is working.
- https://github.com/kyma-project/nats-manager/issues/11
=> Added helm chart for NATS

pkg/manager/nats.go
=> Change nats spelling 

config/rbac/role.yaml, internal/controller/nats/controller.go
To increase the security, RBAC permissions shall be given by name where necessary.
- Add permission for `customresourcedefinitions`
- Add permission for `destinationrules`
- Give (near) full permissions per resource name `evemting-nats` for `configmap`, `secret`, `service`, `statefulset` and `destinationrule`
- Give permissions to `list` and `watch` for all `configmap`, `secret`, `service`, `statefulset` and `destinationrule` resources 
#21
=> Setup RBAC

docs/FlowCharts.md
Add a few flow charts depicting the basic functionality of the NATS manager to the docs.
=> Flow charts

.github/workflows/validatecrd.yml
this adds a simple gh action that tries to apply the nats-crd to a k3d cluster to see if it is complient. very useful, if you work on the crd.
=> add gh action to validate the crd

api/v1alpha1/zz_generated.deepcopy.go, cmd/main.go, config/manager/manager.yaml, pkg/env/config.go, pkg/env/config_test.go
- Made log-level configurable for nats-manager
- https://github.com/kyma-project/nats-manager/issues/53
=> Made log-level configurable for nats-manager

internal/controller/nats/provisioner_test.go, internal/controller/nats/status.go, internal/controller/nats/status_test.go
- Returning error in syncNATSStatusWithErr so reconciliation is triggered
=> Returning error in syncNATSStatusWithErr so reconciliation is triggered

hack/ci/Makefile
- Copy module template to job artifacts
- [sample run](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_nats-manager/82/mfaizanse_test_of_prowjob_pull-nats-module-build/1680827668452347904)
- https://github.com/kyma-project/nats-manager/issues/75
=> Copy module template to job artifacts

.github/workflows/e2e.yml, .github/workflows/pull-with-lifecycle-manager.yaml, .gitignore, Makefile, hack/ci/Makefile, hack/get_module_template_from_build_job.sh
- Replaced github action for `Wait for the 'pull-nats-manager-build' job to succeed` because the old one was not working.
- Added pre-main e2e job with lifecycle-manager
- https://github.com/kyma-project/nats-manager/issues/76
=> Added pre-main e2e jobs with lifecycle-manager

.github/workflows/push-with-lifecycle-manager.yaml, hack/get_module_template_from_build_job.sh
- Added post-main e2e with lifecycle manager job
- https://github.com/kyma-project/nats-manager/issues/76
=> Added post-main e2e with lifecycle manager job

.github/workflows/push-with-lifecycle-manager.yaml
- Fix post main e2e upgrade job
- https://github.com/kyma-project/nats-manager/issues/84
=> Fix post main e2e upgrade job

README.md
- TW review of the NATS Manager README
- ...
- ...
=> review README

docs/contributor/development.md, docs/contributor/governance.md, docs/contributor/installation.md, docs/contributor/testing.md, docs/contributor/troubleshooting.md
- Add documentation for contributors
- Provide a guide for development, testing, installation, governance and troubleshooting
#79
=> NATS Manager Documentation for Contributor

.reuse/dep5, LICENSES/Apache-2.0.txt
- add reuse information as required
=> REUSE metadata proposal

README.md
=> reuse compliance

README.md
- add contribution, code of conduct and license section to the readme
=> add sections required by ospo

api/v1alpha1/nats_types.go, config/rbac/role.yaml, internal/controller/nats/controller.go, internal/controller/nats/controller_test.go, internal/controller/nats/deprovisioner.go, internal/controller/nats/deprovisioner_test.go, internal/controller/nats/integrationtests/controller/integration_test.go, internal/controller/nats/provisioner.go, internal/controller/nats/provisioner_test.go, internal/controller/nats/unit_test.go, pkg/events/events.go, testutils/integration/integration.go, testutils/matchers/nats/matchers.go
- Emit k8s events for relevant state changes
- Adapt the RBAC permissions accordingly
#52
=> k8s Events for State Changes

README.md
- Updated steps to deploy with lifecycle manager
- https://github.com/kyma-project/nats-manager/issues/120
=> Updated steps to deploy with lifecycle manager

sec-scanners-config.yaml
Update deps as per Kyma [main](https://github.com/kyma-project/kyma/blob/4785615d7d9c07c5cffd94754dcbe2d33491d915/resources/eventing/values.yaml#L19-L30).
- #124
=> Update deps as per Kyma main

e2e/cleanup/cleanup_test.go, e2e/natsserver/natsserver_test.go, e2e/setup/setup_test.go, internal/controller/nats/integrationtests/controller/integration_test.go, internal/controller/nats/integrationtests/controllersinglecr/integration_test.go, internal/controller/nats/integrationtests/validation/integration_test.go, testutils/integration/integration.go, testutils/utils.go
Fix checkmarx issues.
- https://github.com/kyma-project/nats-manager/issues/124.
=> Fix checkmarx issues

.env, .github/workflows/create-release.yaml, .version, Makefile, hack/ci/Makefile, scripts/check_image.sh, scripts/check_release_tag.sh, scripts/create_changelog.sh, scripts/create_draft_release.sh, scripts/publish_release.sh, scripts/release.sh, scripts/verify-status.sh
- add release scripts based on the ones created by keda-manager
=> add release scripts based on kyma-project/keda-manager

.github/workflows/create-release.yaml
- run-unit-tests is gone, lets not require it
=> dont wait for run-unit-tests

sec-scanners-config.yaml
- bump nats-manager version in security scan config
=> bump nats-manager in security-scan-config

.github/workflows/create-release.yaml
=> call verify-status

sec-scanners-config.yaml
- bump image for sec scanner config
=> bump image

.version, scripts/check_image.sh, sec-scanners-config.yaml
- bump image before release
- bump module-version
- ...
- ...
- ...
=> bump image before release

.version, scripts/release.sh, sec-scanners-config.yaml
- upload default.yaml
- bump versions
- ...
- ...
- ...
=> upload nats-default-cr to release

sec-scanners-config.yaml
- rename module
- bump image
- ...
- ...
- ...
=> rename module in sec scanner

.version, sec-scanners-config.yaml
Update metadata for nats-manager 0.1.4
=> Update metadata for nats-manager 0.1.4

config/default/kustomization.yaml, config/ui-extensions/kustomization.yaml, config/ui-extensions/nats/details, config/ui-extensions/nats/general, config/ui-extensions/nats/kustomization.yaml, config/ui-extensions/nats/list
Add UI for NATS module.
- https://github.com/kyma-project/nats-manager/issues/144
=> Add UI for NATS module

.version, sec-scanners-config.yaml
- Bump version to 1.0.0
- Use latest image from [here](https://github.com/kyma-project/nats-manager/commit/8da803338d50935262a7159f7cb86e5378fbff99)
=> Bump images for nats-manager release

.version, sec-scanners-config.yaml
Release 1.0.1 version of the NATS module
=> Release 1.0.1 version

config/manager/manager.yaml
for the nats-manager the reference to the priority class was missing. this pr fixes this
=> add missing reference to priorityClass

testutils/options.go
add function for EM tests to create nats CR with error state
https://github.com/kyma-project/eventing-manager/issues/38
=> Implement nats CR with error state function

config/manager/manager.yaml
- Increase memory limit for NATS manager deployment
=> Increase memory limit for NATS manager deployment

.version, sec-scanners-config.yaml
- Update version of nats-manager
- Update image
=> Update version and image for release

.github/workflows/codequality.yml, .github/workflows/pull-with-lifecycle-manager.yaml, .github/workflows/pull-without-lifecycle-manager.yml, .github/workflows/push-with-lifecycle-manager.yaml, .github/workflows/test.yml
changes to docs/ and to Markdown files will not trigger any workflow
=> streamline how github action workflows get triggered

Dockerfile
=> Bump the golang image in the Dockerfile

sec-scanners-config.yaml
Image from PR #197. Details: https://github.com/kyma-project/nats-manager/commit/67159afa4cb671a766565a1b993d3fa3d9f9035c
=> Bump sec-scanner-config.

docs/user/_sidebar.md
- Add `Home` to `_sidebar.md`
- Fix links in `_sidebar.md`
=> Fix the navigation file

sec-scanners-config.yaml
- fix image tag
/kind bug
/area security
- #199
=> Update sec-scanners-config.yaml: fix nats-manager tag

testutils/integration/integration.go, testutils/options.go
Add function to create a NATS CR with warning state
=> Add function to create a NATS CR with warning state

resources/nats/values.yaml, sec-scanners-config.yaml
Updating natsio images
- [prometheus-nats-exporter](https://github.com/nats-io/prometheus-nats-exporter/releases)
- [nats-server-config-reloader](https://hub.docker.com/r/natsio/nats-server-config-reloader/tags)
- [test-infra/#9469](https://github.com/kyma-project/test-infra/pull/9469)
- Solve security issues
=> Bump natsio images

sec-scanners-config.yaml
- update the image use in sec-scanner-config 
The used image is latest build at [europe-docker.pkg.dev/kyma-project/prod/nats-manager](https://console.cloud.google.com/artifacts/docker/kyma-project/europe/prod/nats-manager)
=> bump the image used in sec-scanners-config

.github/scripts/render_and_upload_manifests.sh, .github/workflows/create-release.yaml
This is a cherry-pick of #283 to the `release-1.0`-branch. 
- fix the `image` value when rendering `nats-manger.yaml` in a release (`Create release` ghaw).
=> set the right image for the release (#283)

docs/contributor/testing.md
- Updated a broken link detected during the custom link check testing
=> Fix a link

sec-scanners-config.yaml
- Changed image tag to main in sec-scanners-config, so we do not have to bump the tag everytime.
=> Changed image tag to main in sec-scanners-config

sec-scanners-config.yaml
- Bump image in sec scanner config - release 1.1.0
=> Bump image in sec scanner config - release 1.1.0

sec-scanners-config.yaml
- Bump rc-tag to 1.1.0 in sec-scanners config
=> Bump rc-tag to 1.1.0 in sec-scanners config

sec-scanners-config.yaml
- Bump rc tag to 1.1.0 in sec-scanners config
=> Bump rc tag to 1.1.0 in sec-scanners config

.github/workflows/lint-conventional-prs.yml
- update link for regex to point to correct sample
=> chore: update regex link in action

.github/workflows/codequality.yml, .gitignore, .golangci.yaml, api/v1alpha1/nats_status.go, internal/controller/nats/deprovisioner.go, internal/controller/nats/deprovisioner_test.go, internal/controller/nats/integrationtests/controller/integration_test.go, internal/controller/nats/provisioner.go, internal/controller/nats/provisioner_test.go, internal/controller/nats/status.go, internal/controller/nats/status_test.go, pkg/events/events.go, pkg/k8s/chart/helmrenderer.go, pkg/k8s/chart/releaseinstance.go, pkg/k8s/client.go, pkg/manager/nats.go, pkg/manager/nats_test.go, pkg/manager/options.go, pkg/manager/overrides.go, pkg/nats/client_unit_test.go, testutils/integration/integration.go, testutils/options.go
- Linter config is still local
- Linters:
- gofumpt
- goerr113
- godox
- goconst
- Modify golangci/golangci-lint-action version from 4 to 3. 
Commits: https://github.com/kyma-project/nats-manager/pull/341/commits
=> chore: Linter configuration: gofumpt, goerr113, godox, goconst

Dockerfile, go.mod
- update golang version to 1.22.2
=> chore: update golang version to 1.22.2

.github/workflows/codequality.yml, .github/workflows/test.yml, .gitignore, .golangci.yaml, Makefile, internal/controller/nats/controller.go, internal/controller/nats/controller_test.go, pkg/manager/nats.go, pkg/manager/overrides_test.go, testutils/integration/integration.go, testutils/utils.go
- use local lint configuration
- update linter version to 1.57
=> chore: use local lint configuration

sec-scanners-config.yaml
- bumped sec-scanners-config for release 1.2.0
=> chore: bumped sec-scanners-config for release 1.2.0

resources/nats/templates/statefulset.yaml, resources/nats/values.yaml, sec-scanners-config.yaml
- replace alpine image to signed one. (`europe-docker.pkg.dev/kyma-project/prod/external/alpine:3.19.1`)
- https://github.com/kyma-project/nats-manager/issues/371
=> fix: replace alpine image

resources/nats/templates/statefulset.yaml, resources/nats/values.yaml, sec-scanners-config.yaml
- [Cherry-picked] [replace alpine image to signed one. (`europe-docker.pkg.dev/kyma-project/prod/external/alpine:3.19.1`)](https://github.com/kyma-project/nats-manager/pull/372)
- https://github.com/kyma-project/nats-manager/issues/371
=> fix: replace alpine image [release-1.2 branch]

sec-scanners-config.yaml
- bumped sec-scanners-config for release 1.2.1
=> chore: bumped sec-scanners-config for release 1.2.1

config/ui-extensions/nats/general
- Unify NATS CR's description and the link to the NATS documentation to be consistent with all CR descriptions in Kyma dashboard
https://github.com/kyma-project/kyma/issues/18321
=> Unify NATS CR description in Kyma dashboard

CONTRIBUTING.md
- Update the contributing file
https://github.com/kyma-project/community/issues/926
=> docs: update the contributing file

api/v1alpha1/nats_types.go, config/crd/bases/operator.kyma-project.io_nats.yaml
- Add proper categories for telemetry CRDs according to linked ADR
- ...
- ...
- https://github.com/kyma-project/community/issues/912
=> feat: add proper categories for CRDs

README.md
The file Makefile Helpers has been removed from kubebuilder documentation with this https://github.com/kubernetes-sigs/kubebuilder/pull/4184.
=> docs: remove a broken link

docs/contributor/troubleshooting.md
- Replace Remedy with Solution
- ...
- ...
https://github.com/kyma-project/community/pull/950
=> docs: replace Remedy with Solution

sec-scanners-config.yaml
-  bump the `sec-scanners-config.yaml` for the release of `v1.2.2`
=> chore: bump the sec-scanners-config

.github/workflows/codequality.yml, .github/workflows/pull-e2e-test.yml, .github/workflows/push-e2e-upgrade-test.yaml, .golangci.yaml, Makefile, e2e/scripts/natsbench.sh
- bump golintci from `v1.60.1` to `v2.1.6`
- migrate the `.golangci.yaml` to the new `v2` format
- bump the `golangci-lint-action` from `v6.5.0` to `v8.0.0`
- deactivate a number of linters to be able to merge this PR
- pin the version to `natscli` from `latest` to `v0.1.6` due to breaking changes in the api
follow up #549
=> fix: linter

.github/workflows/create-release.yaml
- add permissions to the release workflow
=> chore: add permissions to release workflow

.github/scripts/render_and_upload_manifests.sh, .github/workflows/create-release.yaml
- add time out and retry in curl command 
=> fix: add timeout
