internal/controller/nats/controller_integration_test.go, internal/controller/nats/integration_test.go, testutils/integration/integration.go
move the integration test into the testutil	package because
- reduces clutter  `/integration/controller/nats`
- reduces confusion over a `_test.go` file that does not contain any tests
- make the integration test reusable in other packages.
- **Related issue(s)**
=> move integration test setup into testutils

api/v1alpha1/nats_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/operator.kyma-project.io_nats.yaml, internal/controller/nats/integrationtests/controller/integration_test.go, internal/controller/nats/integrationtests/validation/integration_test.go, testutils/integration/integration.go
- Fixed envtest setup to run multiple instances and added a validation sample test.
- https://github.com/kyma-project/nats-manager/issues/9
=> Fixed envtest setup to run multiple instances and added a validation sample test

api/v1alpha1/nats_types.go, config/crd/bases/operator.kyma-project.io_nats.yaml, internal/controller/nats/integrationtests/validation/integration_test.go, testutils/integration/integration.go, testutils/matchers/nats/matchers.go, testutils/utils.go
add validation of `spec.jetStream.memStorage`: memStorage can only be enabled if size is not 0.
add validation of `spec.jetStream.fileStorage`: fileStorage cannot be edited once it was set
also, refactored some of the existing tests.
=> add validation of `memStorage` and `fileStorage`

.github/workflows/pull-with-lifecycle-manager.yaml, .github/workflows/push-with-lifecycle-manager.yaml, Makefile, api/v1alpha1/zz_generated.deepcopy.go, e2e/common/fixtures/fixtures.go, e2e/scripts/natsserver.sh, e2e/setup/setup_test.go, hack/ci/Makefile, hack/verify_kyma_status.sh
- Added [pull+push] e2e upgrade from fast-channel to current commit test jobs
- Made e2e test verbose.
- Updated e2e tests to check readiness of nats-manager deployment and NATS CR before starting the test cases.
- https://github.com/kyma-project/nats-manager/issues/84
=> Added e2e upgrade from fast-channel to current commit test jobs

.github/workflows/create-release.yaml
- the tests have already been executed before merging to main, so we can skip them during the release process
=> disable unit tests during release

.version, Makefile, config/crd/bases/operator.kyma-project.io_nats.yaml, config/manager/kustomization.yaml, scripts/release.sh, sec-scanners-config.yaml
- bump image
- bump version
- fix scripts
- ...
- ...
- ...
=> fix release scripts

config/manager/kustomization.yaml, config/manager/priority-class.yaml, e2e/common/fixtures/fixtures.go, e2e/setup/setup_test.go, resources/nats/templates/priority-class.yaml, resources/nats/values.yaml
As part of modularisation, we cannot longer rely on a PriorityClass provided by Kyma, so this PR implements `nats-manager`'s very own ProirityClass
=> add PriorityClass

config/crd/bases/operator.kyma-project.io_nats.yaml, internal/controller/nats/integrationtests/validation/integration_test.go
=> Sync test CRD defaults

.gitignore, Makefile, hack/ci/Makefile, module-config-template.yaml, scripts/release.sh
- Updated make module-build to use config file.
- Added link to documentation
- https://github.com/kyma-project/nats-manager/issues/160
=> Updated make module-build to use config file

Makefile, docs/user/02-configuration.md
- generate CRD-documentation automatically
=> add targets to update crd documentation

docs/user/README.md
=> add info about NATS backend

README.md
Update readme to include steps to install latest NATS manager and CR.
=> Update readme to include steps to install latest NATS manager and CR

.github/workflows/codequality.yml, .github/workflows/pull-with-lifecycle-manager.yaml, .github/workflows/pull-without-lifecycle-manager.yml, .github/workflows/push-with-lifecycle-manager.yaml, .github/workflows/test.yml
We do not need to run tests in our code if we only bump the test scanner config.
=> For tests Ignore changes to the sec-scanner-config.

config/crd/bases/operator.kyma-project.io_nats.yaml, config/default/kustomization.yaml, config/manager/manager.yaml, config/manager/priority-class.yaml, config/rbac/role.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml, internal/controller/nats/integrationtests/validation/integration_test.go, pkg/manager/overrides_test.go, resources/nats/templates/_helpers.tpl, resources/nats/values.yaml
Use common labels for the NATS manager resources.
- https://github.com/kyma-project/nats-manager/issues/221
=> Use common labels for the NATS manager resources

.github/workflows/create-release.yaml
At the current version, the `create-release` workflow does an operation based on a script, which is not available at that point in time. We need to run the `checkout` first.
- run `checkout` before `check_version_format.sh`
https://github.com/kyma-project/nats-manager/issues/245
=> fix the order in which release scripts run

.github/scripts/check-prow-build-job.sh
- add a proper retry-loop in the validation of the prow build job in the `Create-release` workflow (compare to https://github.com/kyma-project/eventing-manager/blob/main/scripts/verify-status.sh)
=> add retry logic to the build jobs validation

resources/nats/values.yaml, sec-scanners-config.yaml, testutils/integration/integration.go
Upgrade prometheus-nats-exporter, nats-server-config-reloader and nats server image in sec scanners config.
**Reason**
We get security issues related to this images
=> Upgrade NATS images to fix security issues

.github/workflows/pull-e2e-test.yml, .github/workflows/pull-e2e-upgrade-test.yaml, .github/workflows/push-e2e-upgrade-test.yaml, Makefile, go.mod
- Bump Go version to `v1.22.0`
=> Bump Golang version to 1.22.0

e2e/common/retry.go
[Staticcheck](https://staticcheck.dev/) does not like the `Retry` functions we use in the `e2e` tests, so let's improve them:
- Simplify the `Retry` and `RetryGet` functions.
**Tests**
Issues with changes would be caught via the `e2e` tests.
**Related**
https://github.com/kyma-project/eventing-manager/pull/503
=> Chore: Simplify retry functions

sec-scanners-config.yaml
- bumped sec-scanners-config for release 1.2.0
=> chore: bumped sec-scanners-config for release 1.2.0

sec-scanners-config.yaml
- bumped sec-scanners-config for release 1.2.1
=> chore: bumped sec-scanners-config for release 1.2.1 [release-1.2 branch]

docs/user/02-configuration.md
- add information about high availability of NATS servers
- https://github.com/kyma-project/nats-manager/issues/358
=> chore: add information about high availability of NATS servers

Dockerfile, go.mod
- update golang version to 1.22.5
- bump golang version in external images: [test-infra/#11286](https://github.com/kyma-project/test-infra/pull/11286)
=> chore: update go version to 1.22.5

.github/workflows/codequality.yml
I was facing the following issue with version 1.57 and Go 1.23:
```
Killed
Error: golangci-lint exit with code 137
```
- golangci-lint version 1.57 has a bug with Go 1.23 (https://github.com/golangci/golangci-lint-action/issues/1094)
=> chore: upgrade golangci-lint version to v1.60.3

.github/workflows/pull-build-image.yaml, .github/workflows/push-build-image.yaml, .github/workflows/tag-build-image.yaml, Dockerfile
- added github action based build jobs.
- changed Dockerfile working directory because of error:
```
2024-09-16T08:07:03.1145549Z ValueError: Dockerfile cannot use /workspace as the working directory. Please switch to another one (e.g., /<module>-workspace). See: https://github.com/GoogleContainerTools/kaniko/issues/3176 and https://github.com/GoogleContainerTools/kaniko/issues/2192
```
=> chore: added github action based build jobs

docs/contributor/testing.md
-  remove prow reference
- https://github.com/kyma-project/eventing-manager/issues/636
=> fix: remove prow reference

e2e/common/retry.go
- make the `retry` functions used in e2e tests linter-compliant
=> fix: retry functions

sec-scanners-config.yaml
- updated sec-scanners-config format
- https://github.com/kyma-project/kyma-companion/issues/384
=> fix: updated sec-scanners-config format
